# --- EXPLICIT NVIDIA DRIVER FIXES ---
env = XDG_SESSION_TYPE,wayland
env = WLR_NO_HARDWARE_CURSORS,1

cursor {
    no_hardware_cursors = true
}
# ------------------------------------

monitor=,preferred,auto,1

# Startup Programs
exec-once = waybar & swaync & nm-applet
exec-once = swaybg -i ~/Pictures/wallpaper.jpg -m fill
exec-once = polkit-gnome-agent

# Environment
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,gtk3

# Keyboard
input {
    kb_layout = de
    repeat_rate = 28
    repeat_delay = 200
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

# The "Modern Rounded" Look
general {
    gaps_in = 2
    gaps_out = 4
    border_size = 1
    col.active_border = rgba(23A5D9ff) rgba(BF8845ff) 45deg
    col.inactive_border = rgba(590202aa)
    layout = dwindle
}

decoration {
    rounding = 15
    blur {
        enabled = true
        size = 5
        passes = 2
    }
    shadow {
        enabled = true
        range = 15
        render_power = 3
        color = rgba(1a1a1aee)
      } 
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 5, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    preserve_split = yes
}

# Keybindings 
$mainMod = SUPER

bind = $mainMod, Return, exec, alacritty
bind = $mainMod, W, killactive, 
bind = $mainMod CTRL, Q, exit, 
bind = $mainMod SHIFT, F, exec, thunar
bind = $mainMod SHIFT, B, exec, firefox
bind = $mainMod, T, togglefloating, 
bind = $mainMod, Space, exec, rofi -show drun -show-icons
bind = $mainMod, F, fullscreen,

# Screenshots
bind = , Print, exec, grim - | wl-copy
bind = $mainMod, S, exec, grim -g "$(slurp)" - | wl-copy

# Audio / Brightness
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t
bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Autoclicker 
bind = $mainMod SHIFT, A, exec, wl-clicker toggle

# Move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Move Windows
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

